/**
 * Agent Download Routes
 *
 * Serves the agent installer and tarball at /dl/.
 * The install.sh and install.ps1 scripts are dynamically generated with the correct cloud URL.
 */

import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { existsSync } from 'fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const dlDir = resolve(__dirname, '..', '..', 'dl');

/**
 * Set up download routes on the Express app.
 * These are PUBLIC (no auth required) — the installer itself handles auth via token.
 */
export function setupDownloadRoutes(app) {

  // GET /dl/install.sh — Dynamic installer script
  // The cloud URL is derived from the request's Host header.
  app.get('/dl/install.sh', (req, res) => {
    const proto = req.secure ? 'https' : 'http';
    const wsProto = req.secure ? 'wss' : 'ws';
    const host = req.headers.host;
    const baseUrl = `${proto}://${host}`;
    const wsUrl = `${wsProto}://${host}`;

    const script = generateInstallScript(baseUrl, wsUrl);
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.setHeader('Content-Disposition', 'inline; filename="install.sh"');
    res.send(script);
  });

  // GET /dl/install.ps1 — Dynamic PowerShell installer for Windows (WSL2)
  app.get('/dl/install.ps1', (req, res) => {
    const proto = req.secure ? 'https' : 'http';
    const host = req.headers.host;
    const baseUrl = `${proto}://${host}`;

    const script = generatePowerShellInstaller(baseUrl);
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.setHeader('Content-Disposition', 'inline; filename="install.ps1"');
    res.send(script);
  });

  // GET /dl/setup-wsl-deps.sh — WSL dependency setup (run as root inside WSL)
  app.get('/dl/setup-wsl-deps.sh', (req, res) => {
    const script = generateWslDepsScript();
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.setHeader('Content-Disposition', 'inline; filename="setup-wsl-deps.sh"');
    res.send(script);
  });

  // GET /dl/49-agent.tar.gz — Agent package tarball
  app.get('/dl/49-agent.tar.gz', (req, res) => {
    const tarball = resolve(dlDir, '49-agent.tar.gz');
    if (!existsSync(tarball)) {
      return res.status(404).send('Agent tarball not found. Run the build script first.');
    }
    res.sendFile(tarball);
  });
}

/**
 * Generate the install.sh script with embedded cloud URL.
 */
function generateInstallScript(baseUrl, wsUrl) {
  return `#!/bin/sh
set -e

# 49Agents Agent Installer
# Generated by cloud server at ${baseUrl}

CLOUD_URL="\${TC_CLOUD_URL:-${wsUrl}}"
DOWNLOAD_URL="\${TC_DOWNLOAD_URL:-${baseUrl}/dl/49-agent.tar.gz}"
INSTALL_DIR="\${TC_INSTALL_DIR:-\$HOME/.49agents}"

echo ""
echo "  49Agents Agent Installer"
echo "  ================================"
echo ""
echo "  Cloud: \$CLOUD_URL"
echo ""

# ---- Check token ----
if [ -z "\$TC_TOKEN" ]; then
  echo "ERROR: TC_TOKEN is required."
  echo ""
  echo "Usage:"
  echo "  curl -fsSL ${baseUrl}/dl/install.sh | TC_TOKEN=<your-token> sh"
  echo ""
  echo "Get a token from the 49Agents UI: click 'Add Machine'"
  exit 1
fi

# ---- Detect OS ----
OS_TYPE="\$(uname -s)"
case "\$OS_TYPE" in
  Darwin) IS_MAC=1 ;;
  Linux)  IS_MAC=0 ;;
  *) echo "Unsupported OS: \$OS_TYPE"; exit 1 ;;
esac

# ---- Check dependencies ----
echo "Checking dependencies..."
MISSING=0
for cmd in node npm tmux; do
  if command -v "\$cmd" >/dev/null 2>&1; then
    echo "  \$cmd: found (\$(command -v \$cmd))"
  else
    echo "  \$cmd: NOT FOUND"
    MISSING=1
  fi
done

# ttyd is optional but recommended
if command -v ttyd >/dev/null 2>&1; then
  echo "  ttyd: found (\$(command -v ttyd))"
else
  echo "  ttyd: NOT FOUND (terminals won't work without it)"
  MISSING=1
fi

if [ "\$MISSING" -eq 1 ]; then
  echo ""
  if [ "\$IS_MAC" -eq 1 ]; then
    if command -v brew >/dev/null 2>&1; then
      printf "Install missing dependencies via Homebrew? [Y/n] "
      read -r REPLY < /dev/tty
      if [ "\$REPLY" = "n" ] || [ "\$REPLY" = "N" ]; then
        echo ""
        echo "  Install manually: brew install tmux node ttyd"
        echo "  Then re-run this installer."
        exit 1
      fi
      echo "Installing missing dependencies via Homebrew..."
      brew install tmux node ttyd 2>&1
      echo ""
      echo "  Dependencies installed."
    else
      echo "ERROR: Missing dependencies and Homebrew is not installed."
      echo ""
      echo "  First install Homebrew:"
      echo '    /bin/bash -c "\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
      echo ""
      echo "  Then re-run this installer."
      exit 1
    fi
  else
    # Linux: offer to auto-install via apt if available
    if command -v apt-get >/dev/null 2>&1; then
      printf "Install missing dependencies automatically? (requires sudo) [Y/n] "
      read -r REPLY < /dev/tty
      if [ "\$REPLY" = "n" ] || [ "\$REPLY" = "N" ]; then
        echo ""
        echo "  Install manually:"
        echo "    sudo apt install tmux nodejs npm"
        echo "    ttyd: https://github.com/tsl0922/ttyd/releases"
        echo ""
        echo "  Then re-run this installer."
        exit 1
      fi
      echo "Installing missing dependencies via apt..."
      sudo apt-get update -qq
      sudo apt-get install -y -qq tmux nodejs npm curl
      # Install ttyd from GitHub releases if missing
      if ! command -v ttyd >/dev/null 2>&1; then
        echo "  Installing ttyd..."
        ARCH="\$(uname -m)"
        if [ "\$ARCH" = "x86_64" ]; then
          TTYD_ARCH="x86_64"
        elif [ "\$ARCH" = "aarch64" ]; then
          TTYD_ARCH="aarch64"
        else
          echo "  WARNING: Unsupported architecture for ttyd: \$ARCH"
          echo "  Install ttyd manually: https://github.com/tsl0922/ttyd/releases"
        fi
        if [ -n "\$TTYD_ARCH" ]; then
          curl -fsSL "https://github.com/tsl0922/ttyd/releases/latest/download/ttyd.\$TTYD_ARCH" -o /tmp/ttyd
          sudo mv /tmp/ttyd /usr/local/bin/ttyd
          sudo chmod +x /usr/local/bin/ttyd
          echo "  ttyd: installed"
        fi
      fi
      echo ""
      echo "  Dependencies installed."
    else
      echo "ERROR: Missing dependencies. Install them first:"
      echo "  tmux, nodejs, npm — use your package manager"
      echo "  ttyd: https://github.com/tsl0922/ttyd/releases"
      exit 1
    fi
  fi
fi

# ---- Download and extract ----
echo ""
echo "Downloading agent from \$DOWNLOAD_URL..."
mkdir -p "\$INSTALL_DIR"
cd "\$INSTALL_DIR"

curl -fsSL "\$DOWNLOAD_URL" -o 49-agent.tar.gz
tar xzf 49-agent.tar.gz
rm 49-agent.tar.gz

# The tarball extracts to agent/ directory
cd agent

# ---- Install npm deps (if not bundled) ----
if [ ! -d "node_modules" ]; then
  echo "Installing dependencies..."
  npm install --production 2>&1 | tail -1
fi

# ---- Configure ----
echo ""
echo "Configuring agent..."
export TC_CLOUD_URL="\$CLOUD_URL"
node bin/49-agent.js login "\$TC_TOKEN"

echo ""
echo "  Agent installed to: \$INSTALL_DIR/agent/"
echo "  Cloud URL: \$CLOUD_URL"
echo ""
echo "  Starting agent now..."
echo "  (Press Ctrl+C to stop)"
echo ""
echo "  To install as a service:"
echo "    cd \$INSTALL_DIR/agent && node bin/49-agent.js install-service"
echo ""

# ---- Start ----
exec node bin/49-agent.js start
`;
}

/**
 * Generate the install.ps1 PowerShell script for Windows (WSL2).
 */
function generatePowerShellInstaller(baseUrl) {
  return `# 49Agents Agent Installer for Windows (WSL2)
# Generated by cloud server at ${baseUrl}
# Usage: $env:TC_TOKEN = "<your-token>"; irm ${baseUrl}/dl/install.ps1 | iex

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "  49Agents Agent Installer (Windows / WSL2)"
Write-Host "  ============================================"
Write-Host ""
Write-Host "  Cloud: ${baseUrl}"
Write-Host ""

# ---- Check token ----
if (-not $env:TC_TOKEN) {
    Write-Host "ERROR: TC_TOKEN is required." -ForegroundColor Red
    Write-Host ""
    Write-Host "Usage:"
    Write-Host '  $env:TC_TOKEN = "<your-token>"'
    Write-Host "  irm ${baseUrl}/dl/install.ps1 | iex"
    Write-Host ""
    Write-Host "Get a token from the 49Agents UI: click 'Add Machine'"
    exit 1
}

# ---- Check WSL2 ----
Write-Host "Checking for WSL2..."

$wslPath = Get-Command wsl.exe -ErrorAction SilentlyContinue
if (-not $wslPath) {
    Write-Host ""
    Write-Host "WSL2 is not installed." -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Options:"
    Write-Host "  [1] Install WSL2 automatically (requires admin privileges)"
    Write-Host "  [2] Show manual instructions and exit"
    Write-Host ""
    $choice = Read-Host "Choose [1/2]"

    if ($choice -eq "1") {
        Write-Host ""
        Write-Host "Installing WSL2 (this may take a few minutes)..."
        Start-Process -FilePath "wsl.exe" -ArgumentList "--install" -Verb RunAs -Wait
        Write-Host ""
        Write-Host "WSL2 installed. You may need to restart your computer." -ForegroundColor Green
        Write-Host "After restarting, run this installer again."
        exit 0
    } else {
        Write-Host ""
        Write-Host "To install WSL2 manually:"
        Write-Host "  1. Open PowerShell as Administrator"
        Write-Host "  2. Run: wsl --install"
        Write-Host "  3. Restart your computer"
        Write-Host "  4. Run this installer again"
        exit 0
    }
}

# Check that a distro is available
$distros = wsl.exe --list --quiet 2>&1 | Where-Object { $_ -and $_ -notmatch "^Windows Subsystem" }
if (-not $distros) {
    Write-Host ""
    Write-Host "WSL2 is installed but no Linux distro found." -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Options:"
    Write-Host "  [1] Install Ubuntu automatically"
    Write-Host "  [2] Show manual instructions and exit"
    Write-Host ""
    $choice = Read-Host "Choose [1/2]"

    if ($choice -eq "1") {
        Write-Host ""
        Write-Host "Installing Ubuntu (this may take a few minutes)..."
        wsl.exe --install -d Ubuntu
        Write-Host ""
        Write-Host "Ubuntu installed. You may need to set up a username/password." -ForegroundColor Green
        Write-Host "After setup, run this installer again."
        exit 0
    } else {
        Write-Host ""
        Write-Host "To install a distro manually:"
        Write-Host "  wsl --install -d Ubuntu"
        Write-Host "After setup, run this installer again."
        exit 0
    }
}

Write-Host "  WSL2: found" -ForegroundColor Green

# ---- Install dependencies inside WSL ----
Write-Host ""
Write-Host "Installing dependencies inside WSL..."

# Run each install step as a direct wsl command — no piping, no scripts, no CRLF.
Write-Host "  Updating apt..."
wsl -u root apt-get update -qq
wsl -u root dpkg --configure -a 2>$null
wsl -u root apt-get --fix-broken install -y -qq 2>$null

Write-Host "  Installing tmux, nodejs, npm, curl..."
wsl -u root apt-get install -y -qq tmux nodejs npm curl
if ($LASTEXITCODE -ne 0) {
    Write-Host "  WARNING: apt install had issues, continuing..." -ForegroundColor Yellow
}

# Install ttyd — break into separate wsl calls for visibility
Write-Host "  Checking ttyd..."
wsl bash -c 'command -v ttyd'
if ($LASTEXITCODE -ne 0) {
    Write-Host "  Downloading ttyd..."
    wsl -u root bash -c 'curl -fsSL -o /tmp/ttyd https://github.com/tsl0922/ttyd/releases/latest/download/ttyd.x86_64 && chmod +x /tmp/ttyd && mv /tmp/ttyd /usr/local/bin/ttyd'
    if ($LASTEXITCODE -eq 0) {
        Write-Host "  ttyd: installed" -ForegroundColor Green
    } else {
        Write-Host "  ttyd: FAILED to install (will try aarch64)..." -ForegroundColor Yellow
        wsl -u root bash -c 'curl -fsSL -o /tmp/ttyd https://github.com/tsl0922/ttyd/releases/latest/download/ttyd.aarch64 && chmod +x /tmp/ttyd && mv /tmp/ttyd /usr/local/bin/ttyd'
        if ($LASTEXITCODE -eq 0) {
            Write-Host "  ttyd: installed (aarch64)" -ForegroundColor Green
        } else {
            Write-Host "  ttyd: FAILED — install manually from https://github.com/tsl0922/ttyd/releases" -ForegroundColor Red
        }
    }
} else {
    Write-Host "  ttyd: already installed" -ForegroundColor Green
}

Write-Host ""
Write-Host "  Dependencies ready." -ForegroundColor Green

# ---- Install agent inside WSL ----
Write-Host ""
Write-Host "Installing 49Agents agent inside WSL..."

# Run entirely inside WSL — no PowerShell piping, no CRLF issues.
# PS double-quotes interpolate $token; everything else runs on the Linux side.
$token = $env:TC_TOKEN
wsl bash -c "TC_TOKEN='$token' curl -fsSL '${baseUrl}/dl/install.sh' | TC_TOKEN='$token' sh"

if ($LASTEXITCODE -ne 0) {
    Write-Host ""
    Write-Host "  ERROR: Agent installation failed." -ForegroundColor Red
    Write-Host "  Check the output above for details."
    exit 1
}

Write-Host ""
Write-Host "  ============================================" -ForegroundColor Green
Write-Host "  49Agents agent installed inside WSL!" -ForegroundColor Green
Write-Host "  ============================================" -ForegroundColor Green
Write-Host ""
Write-Host "  To start the agent:"
Write-Host '    wsl bash -c "~/.49agents/agent/bin/49-agent.js start"'
Write-Host ""
Write-Host "  To check status:"
Write-Host '    wsl bash -c "~/.49agents/agent/bin/49-agent.js status"'
Write-Host ""
Write-Host "  To stop the agent:"
Write-Host '    wsl bash -c "~/.49agents/agent/bin/49-agent.js stop"'
Write-Host ""
`;
}

/**
 * Generate the WSL dependency setup script (runs as root inside WSL).
 */
function generateWslDepsScript() {
  return `#!/bin/bash
set -e

echo "  Updating apt and installing packages..."
apt-get update -qq
apt-get --fix-broken install -y -qq
apt-get install -y -qq tmux nodejs npm curl
echo "  tmux, nodejs, npm, curl: installed"

if ! command -v ttyd > /dev/null 2>&1; then
    echo "  Installing ttyd..."
    ARCH=\\$(uname -m)
    if [ "\\$ARCH" = "x86_64" ]; then
        TTYD_ARCH="x86_64"
    elif [ "\\$ARCH" = "aarch64" ]; then
        TTYD_ARCH="aarch64"
    else
        echo "  WARNING: Unsupported architecture for ttyd: \\$ARCH"
        exit 0
    fi
    curl -fsSL "https://github.com/tsl0922/ttyd/releases/latest/download/ttyd.\\$TTYD_ARCH" -o /tmp/ttyd
    mv /tmp/ttyd /usr/local/bin/ttyd
    chmod +x /usr/local/bin/ttyd
    echo "  ttyd: installed"
else
    echo "  ttyd: already installed"
fi

echo "  All dependencies ready."
`;
}
